language: C++

dist: xenial

sudo: required

install: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsfml-dev

script:
  - make
  - git ls-files src/ | xargs clang-format -i && git diff --exit-code
